### PR TITLE
upgraded the dependencies as in issue #98

### PR DESCRIPTION
**Pull request by Bethel-nz**
### General
Write only what you have added, not what your code does.

### Type

> ℹ️  What types of changes does your code introduce?
     No changes made to the code, just updated the dependencies

> 👉 _Put an `x` in the boxes that apply_

- [x ] Fix
- [ ] Feature

### Describe the changes here (summarized)
updated the dependencies as requested with: `yarn upgrade-interactive`

### CODE REVIEW

**Comment by itsalb3rt** [comment]
Thanks for the PR, I see you added a `pnpm-lock.yaml` file, you can remove this file ? this is because the project use `yarn` instead of `pnpm`

**Comment by Bethel-nz** [comment]
Oh,alright will do that,
Also,i wanted to ask for the landing page. It's based on vue js,which i dont really use, can i rework on it with plain html css and js or react?

**Comment by itsalb3rt** [comment]
Cool thanks!

About the landing page, we use react here the repository [https://github.com/ta-vivo/ta-vivo-landing](https://github.com/ta-vivo/ta-vivo-landing)

**Comment by itsalb3rt** [comment]
Close for inactivity.

**Pull request closed without merging**
